#!/usr/bin/env bash
# fd_phonons_job.sh
# Generate and submit a SLURM jobscript that runs VASP in all subdirectories,
# then collects force constants with phonopy.
#
# Usage:
#   bash fd_phonons_job.sh [options]
#
# Options:
#   -n, --nodes    NUMBER   Number of nodes          (default: 1)
#   -c, --cores    NUMBER   Number of cores per node  (default: 128)
#   -q, --queue    NAME     Queue/partition name      (default: normal)
#   -t, --time     HH:MM:SS Walltime                 (default: 48:00:00)
#   -a, --account  NAME     SLURM account            (default: PHY24018)
#   -h, --help              Show this help and exit
#
# Run from within the phonons/ directory that contains the displacement
# subdirectories (001/, 002/, ...) generated by phonopy.

set -euo pipefail

# ─── Defaults ─────────────────────────────────────────────────────────────────
NODES=1
CORES=128
QUEUE="normal"
TIME="48:00:00"
ACCOUNT="PHY24018"

# ─── Argument parsing (short and long options) ─────────────────────────────────
usage() {
    sed -n '/^# Usage:/,/^[^#]/p' "$0" | grep '^#' | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -n|--nodes)   NODES="$2";   shift 2 ;;
        -c|--cores)   CORES="$2";   shift 2 ;;
        -q|--queue)   QUEUE="$2";   shift 2 ;;
        -t|--time)    TIME="$2";    shift 2 ;;
        -a|--account) ACCOUNT="$2"; shift 2 ;;
        -h|--help)    usage 0 ;;
        *) echo "Unknown option: $1" >&2; usage 1 ;;
    esac
done

ROOT=$PWD
JOBSCRIPT="phonons_vasp_jobscript.sh"

# ─── 1. Discover displacement subdirectories ──────────────────────────────────
mapfile -t DIRS < <(find . -maxdepth 1 -type d ! -name "." | sort | sed 's|^./||')

if [[ ${#DIRS[@]} -eq 0 ]]; then
    echo "No subdirectories found in $ROOT"
    exit 1
fi

echo "Found ${#DIRS[@]} subdirectories:"
printf '  %s\n' "${DIRS[@]}"
echo

# ─── 2. Generate SLURM jobscript ──────────────────────────────────────────────
cat > "$JOBSCRIPT" << EOF
#!/usr/bin/env bash
#SBATCH -J phonons_vasp
#SBATCH -o phonons_vasp.%j.out
#SBATCH -e phonons_vasp.%j.err
#SBATCH -N $NODES
#SBATCH -n $CORES
#SBATCH -p $QUEUE
#SBATCH -t $TIME
#SBATCH -A $ACCOUNT

module purge
module load intel/19.1.1  impi/19.0.9
module load vasp/6.3.0
export OMP_NUM_THREADS=1

ROOT="\$PWD"
DIRS=($(printf '"%s" ' "${DIRS[@]}"))

# Run VASP in each displacement directory
for DIR in "\${DIRS[@]}"; do
    echo "Running VASP in \$DIR"
    cd "\$DIR"

    if [[ -f "COMPLETED" ]]; then
        echo "  Already completed – skipping"
        cd "\$ROOT"
        continue
    fi

    ibrun vasp_std || exit \$?
    touch COMPLETED
    cd "\$ROOT"
done

# Collect force constants with phonopy
echo "Running phonopy to collect force constants..."
PHONOPY_FILES=()
for DIR in "\${DIRS[@]}"; do
    if [[ -f "\$DIR/vasprun.xml" ]]; then
        PHONOPY_FILES+=("\$DIR/vasprun.xml")
    else
        echo "Warning: vasprun.xml not found in \$DIR"
    fi
done

if [[ \${#PHONOPY_FILES[@]} -gt 0 ]]; then
    echo "Processing \${#PHONOPY_FILES[@]} vasprun.xml files"
    phonopy -f "\${PHONOPY_FILES[@]}"
    echo "Phonopy completed successfully."
else
    echo "No vasprun.xml files found – phonopy skipped."
    exit 1
fi

echo "All calculations finished successfully."
EOF

# ─── 3. Submit ────────────────────────────────────────────────────────────────
echo "Submitting: nodes=$NODES  cores=$CORES  queue=$QUEUE  time=$TIME"
sbatch "$JOBSCRIPT"
echo "Use 'squeue -u \$USER' to monitor job status."
